config/routes.rb
Rails.application.routes.draw do
  resources :operations

  root 'operations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/operation.rb
class Operation < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]

  def index
    @operations = Operation.all
  end

  def show; end

  def new
    @operation = Operation.new
  end

  def edit; end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to root_path, notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:entry, :payment_method, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GelatomioApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script
    src="https://code.jquery.com/jquery-3.6.0.js"
    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/operations/_form.html.erb
<div class='form-new'>
  <%= form_with(model: operation) do |form| %>
    <% if operation.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

        <ul>
          <% operation.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <label>
        <%= form.check_box :entry %>
        <span> <%= form.label :entry %></span>
      </label>
    </div>

    <div>
      <%= form.label :payment_method %>
      <%= form.select :payment_method, options_for_select([["Cartão", "Cartão"], ["Pix", "Pix"], ["Dinheiro", "Dinheiro"]]) %>
    </div>

    <div class="input-field col s6">
      <%= form.label :value %>
      <%= form.text_field :value %>
    </div>

    <div class="input-field col s6">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>

    <div class='actions'>
      <% if operation.value %>
        <%= form.submit I18n.t('operations.edit'), class: 'btn btn-success' %>
      <% else %>
        <%= form.submit I18n.t('operations.new'), class: 'btn btn-success' %>
      <% end %>
      <%= link_to I18n.t('operations.back'), operations_path, class: 'btn btn-danger' %>
    </div>
  <% end %>

</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });
</script>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>" class='show-operation'>
  <p>
    <strong> Tipo: </strong>
    <%= operation.entry ? 'Entrada' : 'Saída' %>
  </p>

  <p>
    <strong><%= I18n.t('activerecord.attributes.operation.payment_method') %>:</strong>
    <%= operation.payment_method %>
  </p>

  <p>
    <strong><%= I18n.t('activerecord.attributes.operation.value') %>: R$ </strong>
    <%= operation.value %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= operation.description %>
  </p>

</div>

app/views/operations/edit.html.erb
<h1 class='header'><%= I18n.t('operations.edit_operation') %></h1>

<%= render "form", operation: @operation %>

app/views/operations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class='header'><%= I18n.t('operations.title') %></h1>

<div id="operations" class='body-table'>
  <table>
    <thead>
      <tr>
          <th><%= I18n.t('activerecord.attributes.operation.entry') %></th>
          <th><%= I18n.t('activerecord.attributes.operation.payment_method') %></th>
          <th><%= I18n.t('activerecord.attributes.operation.value') %></th>
          <th></th>
      </tr>
    </thead>

    <tbody>
      <% @operations.each do |operation| %>
        <tr>
          <td><%= operation.entry ? 'Entrada' : 'Saída' %></td>
          <td><%= operation.payment_method %></td>
          <td>R$ <%= operation.value %></td>
          <td>
            <%= link_to "Detalhes", operation_url(operation) %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

    
</div>

<div class='actions-index'>
  <%= link_to I18n.t('operations.new_operation'), new_operation_path, class: 'btn' %>
</div>

app/views/operations/new.html.erb
<h1 class='header'><%= I18n.t('operations.new_operation') %></h1>

<%= render "form", operation: @operation %>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @operation %>

<div class='actions-index show'>
  <%= link_to "Editar", edit_operation_path(@operation), class: 'btn' %>
  <%= link_to I18n.t('operations.back'), operations_path, class: 'btn' %>

  <%#= button_to "Destroy this operation", @operation, method: :delete %>
</div>